version: "3"
services:
  pgfwa:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=company-project-driver-account
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  redis:
    container_name: "redis"
    image: "redis:3.2.0"
    ports:
      - 6379:6379
    volumes:
      - "./data/redis:/var/lib/redis/data"
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_local
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,sns,sqs,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
