apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: project-driver-account-api
  namespace: project-driver-account-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-driver-account-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
