kind: Service
apiVersion: v1
metadata:
  labels:
    app: project-driver-account-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: project-driver-account-api
  namespace: project-driver-account-api
spec:
  selector:
    app: project-driver-account-api
  ports:
    - name: access-port
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: health-port
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
