spring:
  write:
    datasource:
      hikari:
        jdbc-url: jdbc:postgresql://localhost:5432/company-project-driver-account
        username: local
        password: local
        pool-name: company-project-driver-account-api
        minimum-idle: 1
        maximum-pool-size: 20
        connection-timeout: 2000
        leak-detection-threshold: 6000
        schema: public
  read:
    datasource:
      hikari:
        jdbc-url: jdbc:postgresql://localhost:5432/company-project-driver-account
        username: local
        password: local
        pool-name: company-project-driver-account-api-ro
        minimum-idle: 1
        maximum-pool-size: 20
        connection-timeout: 2000
        leak-detection-threshold: 6000
        schema: public
        read-only: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public

# AWS Info
amazon:
  region: us-east-1
  account: 123456789012
  secretKey: foo
  accessKeyId: foo
  useIAMRoles: false
  endpoint: http://localhost:4576/queue
  sqs:
  s3:
    logistics-data:
      bucketName: logistics-data.company.com.br
    local:
      endpoint: http://localhost:4572

cache:
  redis:
    url: redis://localhost:6379

server:
  port: 8085

anonymization:
  enabled: true
  interval:
    cron: 0 * * * * *
    lock:
      least: PT30s
      most: PT50s
  ttl:
    days: 0

identity:
  endpoint: http://localhost:8085
  connectTimeout: 500
  socketTimeout: 500

handler:
  driver-create-or-update:
    workers: 2
    buffer: 2
    maximumMessagesToRead: 5
    queue: DEV_company_IDP_CORE_TO_DRIVER_ACCOUNT_CREATE_OR_UPDATE
    poolingDelay: 100
    threadPollExecutorSize: 1
    waitTime: 5
    visibleTimeout: 600