spring:
  write:
    datasource:
      hikari:
        jdbc-url: jdbc:h2:mem:company-project-driver-account
        username: company-project-driver-account-app
        password: company-project-driver-account-app
        pool-name: company-project-driver-account-api
        minimum-idle: 1
        maximum-pool-size: 20
        connection-timeout: 2000
        leak-detection-threshold: 6000
        schema: company-project-DRIVER-ACCOUNT
  read:
    datasource:
      hikari:
        jdbc-url: jdbc:h2:mem:company-project-driver-account
        username: company-project-driver-account-app
        password: company-project-driver-account-app
        pool-name: company-project-driver-account-api-ro
        minimum-idle: 1
        maximum-pool-size: 20
        connection-timeout: 2000
        leak-detection-threshold: 6000
        schema: company-project-DRIVER-ACCOUNT
        read-only: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: company-project-driver-account

# AWS Info
amazon:
  region: us-east-1

cache:
  redis:
    port: 8099
    url: redis://0.0.0.0:${cache.redis.port}

anonymization:
  enabled: true
  interval:
    cron: 0 * * * * *
    lock:
      least: PT30s
      most: PT50s
  ttl:
    days: 0

identity:
  endpoint: http://localhost:8080
  connectTimeout: 500
  socketTimeout: 500

handler:
  driver-create-or-update:
    workers: 2
    buffer: 2
    maximumMessagesToRead: 5
    queue: DEV_company_IDP_CORE_TO_DRIVER_ACCOUNT_CREATE_OR_UPDATE
    poolingDelay: 100
    threadPollExecutorSize: 1
    waitTime: 5
    visibleTimeout: 600
