info:
  component: company Logistics Driver Account
  project:
    name: project-driver-account-api

spring:
  application:
    name: project-driver-account-api

  profiles:
    active: local

  main:
    banner-mode: "off"

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show-sql: false
        use-sql-comments: false
        format-sql: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non-contextual-creation: true
        ddl-auto: none
        generate-statistics: false

#Redis
cache:
  redis:
    read-timeout: 5
    reconnection-delay: 7
  manager:
    lock-time: 30

server:
  port: 8080

management:
  info:
    git:
      mode: full
  server:
    port: 9999
    servlet:
      context-path: /
  security:
    enable: false
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
  health:
    db:
      enabled: true

driver:
  file:
    url:
      tll-minutes: 1440

tenant-identifier:
  tenant-exceptionally-map:
    us: br
    za: br